### ISSUE TITLE
Please add "-X cgroup" to nrpe.cfg check_all_disks_param

### ISSUE THREAD

**Issue by matthope** [example42/puppet-nrpe#31]
In Ubuntu 16.04, the "check_disk" command from nrpe.cfg fails when run as the "nagios" user.

```
# sudo -u nagios /usr/lib/nagios/plugins/check_disk -w 20% -c 10% -L -X tmpfs 
DISK CRITICAL - /run/lxcfs/controllers/blkio is not accessible: Permission denied
```

However, this works with `-X cgroup` appended.

**Comment by alvagante** [comment]
You can customise the template of the nrpe.cfg file to use using the $nrpe::template parameter of the nrpe class.
